module.exports = [
    {persons: ['Кирилл', 'Даша']},
    {persons: ['Влад', 'Лена']},
    {persons: ['Женя', 'Арина']},
    {persons: ['Дима', 'Катя']},
    {persons: ['Женя', 'Света']},
    {persons: ['Ваня', 'Соня']},
    {persons: ['Денис', 'Элла']},
    {persons: ['Денис', 'Наташа']},
    {persons: ['Ярослав', 'Настя']},
    {persons: ['Коля', 'Катя']},
    {persons: ['Саша', 'Ира']},
    {persons: ['Таня']},
    {persons: ['Алена']},
    {persons: ['Денис']},
    {persons: ['Ваня', 'Настя']},
    {persons: ['Рома']},
    {persons: ['Вова']},
    {persons: ['Женя']}
];